services:
  - type: web
    name: pdfnetra-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false 